dataset_name: thumos
train_split: ['training']
val_split: ['validation']
dataset: {
  json_file: ~/videos/tad-annotations/volleyball_anno.json,
  feat_folder: ~/videos/features/vjepa-b/,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 1,
  input_dim: 768,
  feat_stride: 48,
  num_frames: 16,
  default_fps: 60.0,
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 3456,
}
model: {
  fpn_type: identity,
  backbone_arch: [2, 2, 5],
  embd_dim: 512,
  fpn_dim: 512,
  head_dim: 512,
  n_head: 4,
  n_mha_win_size: 19,
  max_buffer_len_factor: 6.0,
  head_num_layers: 2,
}
opt: {
  type: AdamW,
  learning_rate: 5.0e-4,
  epochs: 90,
  warmup: True,
  warmup_epochs: 10,
  weight_decay: 0.05,
  schedule_type: cosine,
}
loader: {
  batch_size: 16,
  num_workers: 4,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  dropout: 0.2,
  droppath: 0.1,
}
test_cfg: {
  nms_method: soft,
  nms_sigma: 0.5,
  iou_threshold: 0.1,
  min_score: 0.001,
  max_seg_num: 200,
  pre_nms_topk: 2000,
  voting_thresh: 0.7,
  multiclass_nms: False,
  duration_thresh: 0.05,
}
output_folder: ~/videos/tad-checkpoints/actionformer/
