-- 保留被摺疊進這一列的「每一次存檔，以及那次改了什麼」。
--
-- 原本摺疊只累加 repeats、並讓最新一次的 summary 覆蓋掉前一次,於是中間每
-- 一次改了什麼全部消失。這個欄位存的是一個陣列,每筆長這樣:
--
--   {"at": "2026-08-24T14:45:00Z",
--    "changes": [
--      {"op": "edited",  "id": 3,  "fields": {"end": [45.2, 47.8]}},
--      {"op": "added",   "id": 40, "item": {"start": 83.0, "end": 107.0}},
--      {"op": "removed", "id": 12, "item": {"start": 12.0, "end": 30.5}}
--    ]}
--
-- 只存真正改動的欄位前後值,不存整份標註 —— 一次存檔通常是幾十 bytes。
-- 永久保留:出事時最想要的就是舊紀錄。
--
-- 附帶效果:session 的切分本來被固定在寫入當下,現在每次存檔的時間都留著,
-- 日後要調整閒置門檻(目前 5 分鐘)可以重算歷史。
ALTER TABLE audit_events ADD COLUMN saves JSONB NOT NULL DEFAULT '[]'::jsonb;
